### ISSUE TITLE
[AVM Module Issue]: missing documentation for custom_domain_keys parameter of front_door_routes

### ISSUE THREAD

**Issue by MikeDembek** [Azure/terraform-azurerm-avm-res-cdn-profile#38]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

I'm not sure

### (Optional) Module Version

0.1.0

### Description

Hello, the custom_domain_keys attribute is shown in the type block for front_door_routes but it is not otherwise documented or described.  It would be helpful to update the documentation to reflect that the custom_domain_keys attribute links a custom domain with an endpoint.

**Comment by didayal-msft** [comment]
Thanks for the feedback! @MikeDembek . We will add this in the documentation and review other gaps and plug those as well.

For now, if it helps, usage of the attribute is available in the "afd_custom_domain_with_customer_managed_secret" example.

![image](https://github.com/Azure/terraform-azurerm-avm-res-cdn-profile/assets/81250915/64b182f1-7aa2-4d13-b947-228f1b453365)

@Poven795909

**Comment by Poven795909** [comment]
The documentation has been updated. Closing the issue.

**Comment by MikeDembek** [comment]
Hi, I'm still not seeing this in the current docs here:

https://registry.terraform.io/modules/Azure/avm-res-cdn-profile/azurerm/latest 

Am I missing something?

Thanks for your work on this module!

**Comment by didayal-msft** [comment]
Its updated now :) please check again.

**Comment by MikeDembek** [comment]
Confirmed!  Thanks for getting that updated.
