### ISSUE TITLE
[AVM Question/Feedback]: difference between avm-res-cdn-profile and proposed avm-res-network-frontdoor AVM

### ISSUE THREAD

**Issue by MikeDembek** [Azure/terraform-azurerm-avm-res-cdn-profile#39]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Hello, I'm interested in how this module might be used in comparison to the proposed avm-res-network-frontdoor module, it seems like avm-res-cdn-profile covers front door deployments and it's not immediately clear to me what the use case is for a separate front door module.

**Comment by didayal-msft** [comment]
@MikeDembek
AVM Modules are named based on the resource family / resource they create and manage. 
The avm-res-network-frontdoor module will create resource of type microsoft.network/frontdoors a.k.a Azure Front Door (Classic).
https://azure.microsoft.com/en-us/updates/azure-front-door-classic-will-be-retired-on-31-march-2027/

This (avm-res-cdn-profile) resource module creates cdn profile resources which have different SKUs including Azure Front Door Standard/Premium and CDN SKUs.
Here is a detailed comparison of all SKUs
https://learn.microsoft.com/en-us/azure/frontdoor/front-door-cdn-comparison#service-comparison

Hope this helps!

**Comment by didayal-msft** [comment]
@MikeDembek
AVM Modules are named based on the resource family / resource they create and manage. 
The avm-res-network-frontdoor module will create resource of type microsoft.network/frontdoors a.k.a Azure Front Door (Classic).
https://azure.microsoft.com/en-us/updates/azure-front-door-classic-will-be-retired-on-31-march-2027/

This (avm-res-cdn-profile) resource module creates cdn profile resources which have different SKUs including Azure Front Door Standard/Premium and CDN SKUs.
Here is a detailed comparison of all SKUs
https://learn.microsoft.com/en-us/azure/frontdoor/front-door-cdn-comparison#service-comparison

Hope this helps!

**Comment by didayal-msft** [comment]
@MikeDembek I will proceed with closing this issue. Hope the details provided helped.

**Comment by MikeDembek** [comment]
Understood - I was surprised to see that given the upcoming deprecation of AFD classic, I wouldn't have thought an AVM would be created for it.  I appreciate the clarification.
