### ISSUE TITLE
[AVM Module Issue]: support for later azapi versions

### ISSUE THREAD

**Issue by MikeDembek** [Azure/terraform-azurerm-avm-res-cdn-profile#46]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### (Optional) Module Version

0.1.0

### Description

This module pins azapi provider version 1.9, but at least some other AVMs, such as avm-res-network-virtualnetwork, require later versions (~> 1.13 in that example), which prevents concurrent use of those modules.  Could this module be updated to permit later versions of the azapi provider?

Here's the issue I see on execution where the azapi provider version isn't constrained in my config, just in the referenced modules:

`Could not retrieve the list of available versions for provider azure/azapi:
no available releases match the given constraints 1.9.0, ~> 1.13`

**Comment by didayal-msft** [comment]
Thank you @MikeDembek for submitting this feedback. We will review and work to update the version 
cc @Poven795909

**Comment by Poven795909** [comment]
Will test with new AzApi version and will push the changes. Thanks for the feedback

**Comment by Poven795909** [comment]
@MikeDembek, apologies for the delay ! through internal testing and discussion, we have decided to wait for v2 for azapi to be released (tentatively by September end or Oct first week) by Hashicorp this to ensure migration to latest version of azapi doesnt cause any breaking change.
