### ISSUE TITLE
[AVM Module Issue]: custom_block_response_status_code should be optional but validation requires a value

### ISSUE THREAD

**Issue by bel-from-nz** [Azure/terraform-azurerm-avm-res-cdn-profile#85]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.1.3

### Description

In the Front Door Firewall Policies variable the custom block response status code is an optional number. When not supplied in calling the module the validation produces an error that makes this field required.

![Image](https://github.com/user-attachments/assets/477b3845-6dfc-4da8-9f9e-3efa33c932ee)

![Image](https://github.com/user-attachments/assets/a12f25d6-bfa1-4164-b696-6e699e750178)

Error: 

![Image](https://github.com/user-attachments/assets/52e5d467-b142-48ce-ad1e-4b3d26582fc4)

**Comment by Poven795909** [comment]
Thanks we will review and Correct it.

CC: @didayal-msft
