### ISSUE TITLE
[AVM Module Issue]: greater flexibility in azapi provider version

### ISSUE THREAD

**Issue by MikeDembek** [Azure/terraform-azurerm-avm-res-cdn-profile#86]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### (Optional) Module Version

1.3

### Description

Hi, could we get support for non-pinned versions of the azapi provider?  Pinning the provider version (2.0.1 in module version 1.3) limits compatibility with other modules and prevents prompt uptake of fixes in subsequent versions.

**Comment by kewalaka** [comment]
agreed, I would suggest this:

```
    azapi = {
      source  = "Azure/azapi"
      version = ">= 1.13, < 3"
    }
```

the absence of jsonencode/decode also works in later versions of the v1 azapi - as evidenced from the AVM module for container app environments where i copied the above from.

**Comment by Poven795909** [comment]
Thanks for the feedback, we will review and correct it

CC: @didayal-msft

**Comment by Poven795909** [comment]
Fix included in the latest release.
